base:
  alternative_bold_font: ./fonts/Roboto-Medium.ttf
  alternative_font: ./fonts/Roboto-Regular.ttf
  bold_font: ./fonts/AlibabaPuHuiTi-2-85-Bold.otf
  bold_font_size: 1
  font: ./fonts/AlibabaPuHuiTi-2-45-Light.otf
  font_size: 1
  input_dir: ./input
  output_dir: ./output
  quality: 100
global:
  padding_with_original_ratio:
    enable: false
  shadow:
    enable: false
layout:
  elements:
    left_bottom:
      is_bold: false
      name: Model
    left_top:
      is_bold: true
      name: LensModel
    right_bottom:
      is_bold: false
      name: Datetime
      value: Photo by NONE
    right_top:
      is_bold: true
      name: Param
  type: normal_with_right_logo
  white_margin:
    enable: true
    width: 3
logo:
  enable: true
  makes:
    canon:
      id: Canon
      path: ./logos/canon.png
    fujifilm:
      id: FUJIFILM
      path: ./logos/fujifilm.png
    hasselblad:
      id: HASSELBLAD
      path: ./logos/hasselblad.png
    huawei:
      id: HUAWEI
      path: ./logos/xmage.jpg
    leica:
      id: leica
      path: ./logos/leica_logo.png
    nikon:
      id: NIKON
      path: ./logos/nikon.png
    olympus:
      id: Olympus
      path: ./logos/olympus_blue_gold.png
    panasonic:
      id: Panasonic
      path: ./logos/panasonic.png
    pentax:
      id: PENTAX
      path: ./logos/pentax.png
    rioch:
      id: RIOCH
      path: ./logos/ricoh.png
    sony:
      id: SONY
      path: ./logos/sony.png
  position: right
param:
  focal_length:
    use_equivalent_focal_length: false
